Hotfix/save custom view state
aiqfome/aiqInput pull request #44
Opened 2022-06-20 20:19 UTC by matheus-souza

migrate components to kotlin
implementing safe proccess death in components

2022-06-22 18:45 UTC, Bianchiniii commented on aiqcomponents/src/main/java/com/aiqfome/aiqcomponents/selector/Selector.kt
> +            typedArray.getColor(
aqui dava pra usar uma scope function with(typeArray), deixaria o código mais limpo

2022-06-22 18:49 UTC, Bianchiniii commented on aiqcomponents/src/main/java/com/aiqfome/aiqcomponents/selector/Selector.kt
> +        binding.inputLayout.isEnabled = enabled
aqui tbm daria pra usar alguma scope func

2022-06-22 19:07 UTC, FelipeKoga requested changes

2022-06-22 19:07 UTC, FelipeKoga commented on aiqcomponents/src/main/java/com/aiqfome/aiqcomponents/adapters/view_holders/IconItemViewHolder.kt
> +            } else View.VISIBLE
se estiver disponível a extension no projeto, poderia ser resumido em "tvSubtitle.isInvisible = item.subTitle.isNullOrEmpty()"

2022-06-22 19:07 UTC, FelipeKoga commented on aiqcomponents/src/main/java/com/aiqfome/aiqcomponents/adapters/view_holders/TextItemViewHolder.kt
> +            } else View.VISIBLE
mesma sugestão da classe IconItemViewHolder

2022-06-22 19:07 UTC, FelipeKoga commented on aiqcomponents/src/main/java/com/aiqfome/aiqcomponents/selector/Selector.kt
> +        Log.i("SavedState", "onRestoreInstanceState")
tem alguns logs nessa classe, é para mante-los?

2022-06-22 19:07 UTC, FelipeKoga commented on aiqcomponents/src/main/java/com/aiqfome/aiqcomponents/sheets/ListBottomSheet.kt
> +    private val binding: LayoutBottomSheetListBinding get() = _binding!!
faltou limpar o _binding no onDestroyView

2022-06-22 19:07 UTC, FelipeKoga commented on aiqcomponents/src/main/java/com/aiqfome/aiqcomponents/sheets/SearchableListBottomSheet.kt
> +    private var _binding: LayoutBottomSheetSearchableListBinding? = null
faltou limpar o _binding no onDestroyView

2022-06-22 19:07 UTC, FelipeKoga commented on aiqcomponents/src/main/java/com/aiqfome/aiqcomponents/textinput/TextInput.kt
> +        Log.i("SavedState", "onSaveInstanceState")
nessa classe também tem alguns logs, é para mante-los?

2022-06-22 19:24 UTC, Bianchiniii reviewed
add comments

2022-06-24 20:05 UTC, AnthoniIP approved these changes, later dismissed

2022-06-24 20:05 UTC, tonimadev commented on aiqcomponents/src/main/java/com/aiqfome/aiqcomponents/textinput/TextInput.kt
> +            typedArray.getResourceId(R.styleable.TextInput_textAppearance, -1).run {
Esses 0s e -1s não poderiam virar constantes?

2022-07-28 13:36 UTC, Bianchiniii approved these changes

2022-07-28 16:59 UTC, FelipeKoga approved these changes

2022-07-28 17:00 UTC, merged